### ISSUE TITLE
Implement image viewer screensaver

### ISSUE THREAD

**Issue by brunobraga** [brunobraga/termsaver#12]
It would be nice to have this with termsaver:

http://csl.sublevel3.org/jp2a/

**Comment by EddieDover** [comment]
The two examples provided write to files and are a bit big dependency wise. I have found one example that displays directly to terminal. https://github.com/yattsu/image_to_ascii

It could be adapted and folded into termsaver but I'm not sure how you feel about this. I've started a branch but will wait for your input before continuing on.

**Comment by brunobraga** [comment]
I like this!

Given the code is not a fully fledged program (does not contain any specs on copyright either), I could suggest that we invite the owner of that script to contribute to this branch but implement his concept to a screen here we could use.

Couple of options come to mind:
- path -> if a file (image) then just prints it out (maybe have further option to re-print it slowly like line by line, sleep, then re-do)
     -> if a folder, does the above for all images available in folder

How about that?

**Comment by EddieDover** [comment]
> 
> 
> I like this!
> 
> Given the code is not a fully fledged program (does not contain any specs on copyright either), I could suggest that we invite the owner of that script to contribute to this branch but implement his concept to a screen here we could use.

I can reach out to the author if you'd like and see what they have to say?

> 
> Couple of options come to mind:
> 
>     * path -> if a file (image) then just prints it out (maybe have further option to re-print it slowly like line by line, sleep, then re-do)
>       -> if a folder, does the above for all images available in folder
> 
> 
> How about that?

I was thinking something similar and I've already made a few changes to the filereader so it supports binary files via an optional parameter.

**Comment by brunobraga** [comment]
Great contribution Eddie, please proceed!

**Comment by brunobraga** [comment]
Make sure you update your branch with the latest code from master.

**Comment by EddieDover** [comment]
Closing this since we merged the relevant PR years ago.
