### ISSUE TITLE
starwars saver does not come to the center of the window

### ISSUE THREAD

**Issue by wkentaro** [brunobraga/termsaver#19]
<img width="1280" alt="screen shot 2015-08-20 at 3 08 06 pm" src="https://cloud.githubusercontent.com/assets/4310419/9376847/5ac858d6-474d-11e5-9e4a-fe77247ae06c.png">

It comes always upper-left.

**Comment by brunobraga** [comment]
Thanks. Can you report the command you used to reproduce this? I worked before on the starwars but haven't released it.

**Comment by wkentaro** [comment]
* Max OSX 10.10
* installed termsaver via pip
```
$ termsaver starwars
```

**Comment by brunobraga** [comment]
Wow, it should not be there. The main package does not contain it neither
does the main code... Need to check how PIP is reading the package from.

On Friday, 21 August 2015, Kentaro Wada <notifications@github.com> wrote:

>
>    - Max OSX 10.10
>    - installed termsaver via pip
>
> $ termsaver starwars
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brunobraga/termsaver/issues/19#issuecomment-133262425>
> .
>


-- 


*--Bruno Braga*
bruno@brunobraga.net
+61-452-212-910

**Comment by brunobraga** [comment]
Dealing with this in Issue #26
