### ISSUE TITLE
termsaver clock - Friday, 11st March 2016

### ISSUE THREAD

**Issue by sirgrim** [brunobraga/termsaver#23]
The clock says Friday, 11st March 2016.

Is this a bug on the system clock termsaver uses, or something in termsaver? 'st' works fine for 1st, 21st, 31st, but 11st just sounds weird.

**Comment by brunobraga** [comment]
Great find.

Would appreciate if you submit a pull request if you have a fix, or else I
will try to do this when I can.

Thanks for raising it!
