### ISSUE TITLE
Incorrect URL for Django Source in Help for TermSaver

### ISSUE THREAD

**Issue by Zzyzx-Wolfe** [brunobraga/termsaver#29]
In TermSaver v.0.3, if you run `termsaver programmer` without a path, part of the error message states:
```
    If you have access to subversion, you may download it at:
        svn co https://code.djangoproject.com/svn/django/trunk/ django-trunk
```

However, Django no longer uses subversion, so the it should be updated to read:
```
    If you have access to git, you may download it at:
        git clone https://github.com/django/django.git
```

Cheers and thanks for the awesome tools,
Zzyzx

**Comment by brunobraga** [comment]
Thanks
