### ISSUE TITLE
Requesting new screensaver porting from javascript

### ISSUE THREAD

**Issue by SubhamBurnwal** [brunobraga/termsaver#48]
### A series of interactive screensavers maybe?
[**Spirits: cursor-controlled particle simulation with ASCII**](http://nkwiatek.com/experiments/ascii)

**Comment by brunobraga** [comment]
Hum... I think the purpose of the screensaver concept is to keep your screen busy while you are idle.

Termsaver was designed using simple STDOUT, so moving to something like you are suggesting involves a complete redesign using  ncurses or similar.
