### ISSUE TITLE
Can't install on Ubuntu Server 21.04 on raspberry pi 4

### ISSUE THREAD

**Issue by anarchy89** [brunobraga/termsaver#49]
I am trying to install termsaver on my raspberry pi 4 running ubuntu server 21.04.

I tried `sudo apt update` and `sudo apt install termsaver`, but it says no such package.

I tried to add `ppa:bruno-braga/termsaver` but it doesn't work.

I also tried to pip install but theres an error.

Is there a way to do it?

**Comment by brunobraga** [comment]
Apologies, all these are out-dated now... have you tried pip install?

**Comment by pstils** [comment]
Thanks @brunobraga,

I'm in the same boat, but running Raspberry Pi OS, having tried exactly the same steps as @anarchy89. 

`sudo pip install termsaver` results in:

`ERROR: Could not find a version that satisfies the requirement termsaver`
`ERROR: No matching distribution found for termsaver`

**Comment by pstils** [comment]
Sorry, I think perhaps the more relevant error is: 

`SyntaxError: Missing parentheses in call to 'print'. Did you mean print(""")?` 
 
You'll know more than I, but from a brief google this appears to be a python version related thing?

**Comment by EddieDover** [comment]
@pstils and @anarchy89:

The PyPI package (that pip reads from) is from 2018, so it is definitely not up to date with the current codebase.

For a short-term solution, you should be able to check out the repo and symlink the 'termsaver' file into your bin path. (Though I'm not sure if there are required packages you'll need, off the top of my head.)

I'll start working on a possible CI/CD solution to get our PyPI package up to date sometime this week between my medical appointments.
