### ISSUE TITLE
Add a "quit on any input" option

### ISSUE THREAD

**Issue by xenolune** [brunobraga/termsaver#51]
Another great addition would be the ability to quit termsaver with any input, like `cmatrix -s`, instead of necessarily having to SIGINT out of it.

**Comment by brunobraga** [comment]
Looking for volunteers... if you can help implement this, I'd welcome the pull request.

**Comment by EddieDover** [comment]
> Looking for volunteers... if you can help implement this, I'd welcome the pull request.

Shouldn't be too hard to implement but we'll most likely need a library like keyboard or pyinput as a requirement. What are your feelings about that @brunobraga?

**Comment by EddieDover** [comment]
Just to follow up. I was able to implement this pretty easily using a pynput keyboard listener. The only real caveat (other than adding another dependency or two because of pynput) is that it isn't immediate since it has to wait for the next 'tick' of the screen. It's minor, a second or less.

**Comment by brunobraga** [comment]
Awesome find @EddieDover . My approach to this is:
- let's keep the termsaver as simple as possible (as requirements for installation)
- we can recommend in the --help section the additional modules that, if installed, can improve the experience (e.g. colorama, pynput, or larger modules)

Then to implement this you just wrap it (when the function is called, you don't action if the module is not available)... something like that perhaps?

**Comment by EddieDover** [comment]
PR #52 is available for review.
