### ISSUE TITLE
Unable to install with apt.

### ISSUE THREAD

**Issue by NoneyaB** [brunobraga/termsaver#53]
When installing on a raspberry pi running Raspberry Pi OS Lite (64 bit) [Debian Bullseye] the following occurs.

pi@raspberrypi:~ $ sudo apt-get install termsaver
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package termsaver
pi@raspberrypi:~ $

**Comment by Et-17** [comment]
I am having the same problem on Ubuntu 20.04.3 LTS x86_64 with 5.11.0-46-generic kernel

**Comment by EddieDover** [comment]
@NoneyaB @Et-17 Whatever exists currently on apt is absolutely ancient and existed before my joining the project. That said, pip support is coming very soon. I expect to have a PR up within the next few days and once approved you should be able to grab termsaver via pip or build from source. I'll tag this issue when it's ready.
