### ISSUE TITLE
Unable to install from source

### ISSUE THREAD

**Issue by Dexter8242** [brunobraga/termsaver#55]
Hi! 
When I try to install using `sudo python /home/dexter/termsaver/setup.py install`, it says the following:
Traceback (most recent call last):
  File "/home/dexter/termsaver/setup.py", line 56, in <module>
    'termsaver.mo')]) for lang in os.listdir('locale')]
FileNotFoundError: [Errno 2] No such file or directory: 'locale'

I'm on Fedora 36.

**Comment by EddieDover** [comment]
Just an FYI @Dexter8242, I've got a branch that will be going up for PR soon that should allow you to build the package from source. This new branch will also prepare termsaver for distribution via pip. It seems the `python setup.py install` method is deprecated, but you should (soon!) be able to simply `python -m build` inside the source folder and have it produce a tar.gz and a whl file.  I'll make sure to tag this issue when the time is ready.
