### ISSUE TITLE
Broken installing with pip

### ISSUE THREAD

**Issue by LeviiLovie** [brunobraga/termsaver#66]
Hello, today I tried to install your app to Ubuntu Server 20.04, I have last version of pip installed here, how you're saying in README.md, i ran ```sudo pip install termsaver``` . And got that output:
```
Collecting termsaver
  Using cached termsaver-0.4.tar.gz (46 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-zk6wuiq_/termsaver_62fe2076d8a1406e9920047884ff730c/setup.py", line 101
          print """
          ^^^^^^^^^
      SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
I'm not Python developer, (more i know in golang), but how i can undersatnd, it have Syntax Error. And pip i ssaying, that ```note: This is an issue with the package mentioned above, not pip.```. 
So, if you can, please, explain to me, that i did wrong, or fix that error.
Thank you for putting your time in this post.

**Comment by EddieDover** [comment]
@LeviiLovie You're correct, the instructions still point to a pip installation but the version on pip is very oudated. We're still getting caught up with a new pipeline to publish the most recent build out.  

If you're comfortable building from source, clone the repo and inside the folder you can `python -m build` and it generate a whl file in the /dist folder that you can install with 'pip'.

If none of that made sense to you, please reach out and I'll guide you through everything.

I'll also see about updating the readme with better instructions, and I'll see about finding some time this weekend to get the newest packages on pip.

**Comment by EddieDover** [comment]
@LeviiLovie Please try installing from pip again and let me know how things go. I've updated our build system and pushed a new 0.6.0 build to pypi in #67
