### ISSUE TITLE
Add StarWars Asciimation as screensaver option

### ISSUE THREAD

**Issue by brunobraga** [brunobraga/termsaver#9]
Source: http://www.asciimation.co.nz/

**Comment by EddieDover** [comment]
I have a branch with this feature mostly working if we're still interested in it?

The Asciimation has been moved away from a jar file, so it took a lot of digging to find on the original text file that was used to hold the animation frame data. 

The frame display speed may need to be adjusted, it seems too fast a times, but I've implemented it the same way he details in the [FAQ](http://www.asciimation.co.nz/asciimation/ascii_faq.html)

**Comment by brunobraga** [comment]
Yes please. Great help Eddie.

I never got the chance to complete the "plugin" concept for termsaver (makes sense specially for cases in which you have to add multiple/large dependencies to the main program... not sure if you think this should be one? if we have to save the original source inside termsaver, I'd recommend doing that, and remember to comply with the site's copyright rules)

**Comment by EddieDover** [comment]
> 
> 
> Yes please. Great help Eddie.
> 
> I never got the chance to complete the "plugin" concept for termsaver (makes sense specially for cases in which you have to add multiple/large dependencies to the main program... not sure if you think this should be one? if we have to save the original source inside termsaver, I'd recommend doing that, and remember to comply with the site's copyright rules)

No source was used other than the sw1.txt file that has the actual frame data.  I haven't dug into the copyright rules but I could reach out to the maintainer directly and see if they're willing to provide an updated copy and/or give it their blessing? Attribution isn't a problem, I imagine, and some is already included in the first few frames of the animation.  The major issue I have with this is that the animation itself is 1,875Kb. 

At first, I was parsing it out into frames and timing data on screen init, but after seeing how each screen is initalized multiple times no matter if it's used or not, I've taken steps to load it in at first run cycle instead. It causes a bit of a delay, but that's better than having termsaver itself delay anytime any command or screen was loaded.

**Comment by brunobraga** [comment]
That's great, please proceed!
